import { defineStore } from 'pinia'

export const useMoviesStore = defineStore('movies', {
  state: () => ({
    movies: [
      { id: 1, title: 'Parasite', year: 2019, genre: 'Thriller, Drama', length: 132, actors: ['Kang-ho Song','Sun-kyun Lee','Yeo-jeong Cho','Woo-sik Choi'], description: 'A poor family schemes to become employed by a wealthy family. Dark comedy and social commentary.', image: '/images/parasite.jpg', rating: 8.6, language: 'KR', subtitles: true, toWatch: false },
      { id: 2, title: 'Amélie', year: 2001, genre: 'Romantic Comedy', length: 122, actors: ['Audrey Tautou','Mathieu Kassovitz','Rufus'], description: 'A whimsical Parisian woman decides to help others while grappling with her own loneliness.', image: '/images/amelie.jpg', rating: 8.3, language: 'FR', subtitles: true, toWatch: false },
      { id: 3, title: 'Spirited Away', year: 2001, genre: 'Animation, Fantasy', length: 125, actors: ['Rumi Hiiragi','Miyu Irino','Mari Natsuki'], description: 'A young girl navigates a world of spirits and gods to save her parents.', image: '/images/spirited_away.jpg', rating: 8.6, language: 'JP', subtitles: true, toWatch: false },
      { id: 4, title: 'City of God', year: 2002, genre: 'Crime, Drama', length: 130, actors: ['Alexandre Rodrigues','Leandro Firmino','Phellipe Haagensen'], description: 'Two boys grow up in a violent neighborhood of Rio de Janeiro and choose different paths.', image: '/images/city_of_god.jpg', rating: 8.6, language: 'PT', subtitles: true, toWatch: false },
      { id: 5, title: 'Pans Labyrinth', year: 2006, genre: 'Fantasy, War', length: 118, actors: ['Ivana Baquero','Sergi López','Maribel Verdú'], description: 'A young girl discovers a mysterious labyrinth in post-Civil War Spain.', image: '/images/pans_labyrinth.jpg', rating: 8.2, language: 'ES', subtitles: true, toWatch: false },
      { id: 6, title: 'The Intouchables', year: 2011, genre: 'Comedy, Drama', length: 112, actors: ['François Cluzet','Omar Sy','Anne Le Ny'], description: 'An unlikely friendship forms between a wealthy quadriplegic and his caregiver.', image: '/images/the_intouchables.jpg', rating: 8.5, language: 'FR', subtitles: true, toWatch: false },
      { id: 7, title: 'Oldboy', year: 2003, genre: 'Thriller, Mystery', length: 120, actors: ['Min-sik Choi','Ji-tae Yu','Hye-jeong Kang'], description: 'A man is imprisoned for 15 years and seeks revenge upon release.', image: '/images/oldboy.jpg', rating: 8.4, language: 'KR', subtitles: true, toWatch: false },
      { id: 8, title: 'The Lives of Others', year: 2006, genre: 'Drama, Thriller', length: 137, actors: ['Ulrich Mühe','Martina Gedeck','Sebastian Koch'], description: 'A Stasi officer becomes involved in the lives of the people he monitors.', image: '/images/lives_of_others.jpg', rating: 8.4, language: 'DE', subtitles: true, toWatch: false },
      { id: 9, title: 'Crouching Tiger, Hidden Dragon', year: 2000, genre: 'Action, Adventure', length: 120, actors: ['Chow Yun-fat','Michelle Yeoh','Zhang Ziyi'], description: 'A legendary warrior and a mysterious swordswoman cross paths in Qing Dynasty China.', image: '/images/crouching_tiger.jpg', rating: 7.9, language: 'ZH', subtitles: true, toWatch: false },
      { id: 10, title: 'Let the Right One In', year: 2008, genre: 'Horror, Drama', length: 115, actors: ['Kåre Hedebrant','Lina Leandersson','Per Ragnar'], description: 'A young boy befriends a peculiar girl who turns out to be a vampire.', image: '/images/let_the_right_one_in.jpg', rating: 7.9, language: 'SV', subtitles: true, toWatch: false },
      { id: 11, title: 'Roma', year: 2018, genre: 'Drama', length: 135, actors: ['Yalitza Aparicio','Marina de Tavira','Diego Cortina Autrey'], description: 'A year in the life of a middle-class family in Mexico City in the early 1970s.', image: '/images/roma.jpg', rating: 7.7, language: 'ES', subtitles: true, toWatch: false },
      { id: 12, title: 'A Separation', year: 2011, genre: 'Drama, Thriller', length: 123, actors: ['Peyman Moaadi','Leila Hatami','Sareh Bayat'], description: 'A couple faces the challenges of divorce and moral dilemmas in Iran.', image: '/images/a_separation.jpg', rating: 8.3, language: 'FA', subtitles: true, toWatch: false },
      { id: 13, title: 'Your Name', year: 2016, genre: 'Animation, Romance', length: 106, actors: ['Ryunosuke Kamiki','Mone Kamishiraishi','Ryo Narita'], description: 'Two teenagers mysteriously swap bodies and develop a deep connection.', image: '/images/your_name.jpg', rating: 8.4, language: 'JP', subtitles: true, toWatch: false },
      { id: 14, title: 'The Hunt', year: 2012, genre: 'Drama', length: 115, actors: ['Mads Mikkelsen','Thomas Bo Larsen','Annika Wedderkopp'], description: 'A man faces false accusations that destroy his life and community.', image: '/images/the_hunt.jpg', rating: 8.3, language: 'DA', subtitles: true, toWatch: false },
      { id: 15, title: 'The Secret in Their Eyes', year: 2009, genre: 'Crime, Drama', length: 129, actors: ['Ricardo Darín','Soledad Villamil','Pablo Rago'], description: 'A retired legal counselor writes a novel hoping to find closure for an unsolved crime.', image: '/images/secret_in_their_eyes.jpg', rating: 8.2, language: 'ES', subtitles: true, toWatch: false },
      { id: 16, title: 'Train to Busan', year: 2016, genre: 'Action, Horror', length: 118, actors: ['Gong Yoo','Ma Dong-seok','Jung Yu-mi'], description: 'Passengers struggle to survive a zombie outbreak on a train in South Korea.', image: '/images/train_to_busan.jpg', rating: 7.6, language: 'KR', subtitles: true, toWatch: false },
      { id: 17, title: 'Incendies', year: 2010, genre: 'Drama, Mystery', length: 131, actors: ['Lubna Azabal','Mélissa Désormeaux-Poulin','Maxim Gaudette'], description: 'Twins uncover their mother’s hidden past after her death.', image: '/images/incendies.jpg', rating: 8.2, language: 'FR', subtitles: true, toWatch: false },
      { id: 18, title: 'Battle Royale', year: 2000, genre: 'Action, Thriller', length: 114, actors: ['Tatsuya Fujiwara','Aki Maeda','Tarô Yamamoto'], description: 'A class of students is forced to fight to the death by the government.', image: '/images/battle_royale.jpg', rating: 7.7, language: 'JP', subtitles: true, toWatch: false },
      { id: 19, title: 'The Salesman', year: 2016, genre: 'Drama, Thriller', length: 125, actors: ['Shahab Hosseini','Taraneh Alidoosti','Babak Karimi'], description: 'A couple’s relationship is tested after a traumatic incident.', image: '/images/the_salesman.jpg', rating: 7.8, language: 'FA', subtitles: true, toWatch: false },
      { id: 20, title: 'Good Bye Lenin!', year: 2003, genre: 'Comedy, Drama', length: 121, actors: ['Daniel Brühl','Katrin Saß','Chulpan Khamatova'], description: 'A son protects his mother from the shock of a reunited Germany.', image: '/images/good_bye_lenin.jpg', rating: 7.7, language: 'DE', subtitles: true, toWatch: false },
      { id: 21, title: 'La La Land', year: 2016, genre: 'Musical, Romance', length: 128, actors: ['Ryan Gosling','Emma Stone','John Legend'], description: 'A jazz musician and an aspiring actress fall in love in Los Angeles.', image: '/images/la_la_land.jpg', rating: 8.0, language: 'EN', subtitles: false, toWatch: false },
      { id: 22, title: 'The Handmaiden', year: 2016, genre: 'Thriller, Romance', length: 144, actors: ['Kim Min-hee','Ha Jung-woo','Kim Tae-ri'], description: 'A con woman is hired to help a wealthy heiress, but nothing is as it seems.', image: '/images/handmaiden.jpg', rating: 8.1, language: 'KR', subtitles: true, toWatch: false },
      { id: 23, title: 'Life is Beautiful', year: 1997, genre: 'Comedy, Drama', length: 116, actors: ['Roberto Benigni','Nicoletta Braschi','Giorgio Cantarini'], description: 'A man uses humor to protect his son during the Holocaust.', image: '/images/life_is_beautiful.jpg', rating: 8.6, language: 'IT', subtitles: true, toWatch: false },
      { id: 24, title: 'Ida', year: 2013, genre: 'Drama', length: 82, actors: ['Agata Trzebuchowska','Agata Kulesza','Dawid Ogrodnik'], description: 'A young nun discovers a family secret in 1960s Poland.', image: '/images/ida.jpg', rating: 7.4, language: 'PL', subtitles: true, toWatch: false },
      { id: 25, title: 'Capernaum', year: 2018, genre: 'Drama', length: 126, actors: ['Zain Al Rafeea','Yordanos Shiferaw','Boluwatife Treasure Bankole'], description: 'A young boy sues his parents for neglect in Beirut.', image: '/images/capernaum.jpg', rating: 8.4, language: 'AR', subtitles: true, toWatch: false },
      { id: 26, title: 'Shoplifters', year: 2018, genre: 'Drama', length: 121, actors: ['Lily Franky','Sakura Ando','Mayu Matsuoka'], description: 'A family of small-time thieves take in a neglected girl and form bonds.', image: '/images/shoplifters.jpg', rating: 7.9, language: 'JP', subtitles: true, toWatch: false },
      { id: 27, title: 'The Platform', year: 2019, genre: 'Horror, Sci-Fi', length: 94, actors: ['Iván Massagué','Zorion Eguileor','Antonia San Juan'], description: 'Prisoners in a vertical jail discover the cruelty of sharing limited food.', image: '/images/the_platform.jpg', rating: 7.0, language: 'ES', subtitles: true, toWatch: false },
      { id: 28, title: 'Memories of Murder', year: 2003, genre: 'Crime, Drama', length: 131, actors: ['Kang-ho Song','Kim Sang-kyung','Roe-ha Kim'], description: 'Detectives struggle to solve a series of brutal murders in 1980s South Korea.', image: '/images/memories_of_murder.jpg', rating: 8.1, language: 'KR', subtitles: true, toWatch: false }, 
      { id: 29, title: 'Festen', year: 1998, genre: 'Drama', length: 105, actors: ['Ulrich Thomsen','Henning Moritzen','Paprika Steen'], description: 'A family reunion turns shocking when dark secrets are revealed.', image: '/images/festen.jpg', rating: 8.0, language: 'DA', subtitles: true, toWatch: false },
      { id: 30, title: 'A Fantastic Woman', year: 2017, genre: 'Drama', length: 104, actors: ['Daniela Vega','Francisco Reyes','Luis Gnecco'], description: 'A transgender woman faces grief and discrimination after her partner dies.', image: '/images/fantastic_woman.jpg', rating: 7.2, language: 'ES', subtitles: true, toWatch: false },
      { id: 31, title: 'The Wailing', year: 2016, genre: 'Horror, Mystery', length: 156, actors: ['Kwak Do-won','Hwang Jung-min','Chun Woo-hee'], description: 'A rural village is terrorized by mysterious deaths and sickness.', image: '/images/the_wailing.jpg', rating: 7.5, language: 'KR', subtitles: true, toWatch: false },
      { id: 32, title: '4 Months, 3 Weeks and 2 Days', year: 2007, genre: 'Drama', length: 113, actors: ['Anamaria Marinca','Laura Vasiliu','Vlad Ivanov'], description: 'A young woman helps her friend during a secret abortion in communist Romania.', image: '/images/4_months_3_weeks_2_days.jpg', rating: 7.9, language: 'RO', subtitles: true, toWatch: false },
      { id: 33, title: 'Nobody Knows', year: 2004, genre: 'Drama', length: 141, actors: ['Yūya Yagira','Momoko Shimizu','Hanae Kan'], description: 'Four siblings are left to survive alone when their mother abandons them.', image: '/images/nobody_knows.jpg', rating: 8.1, language: 'JP', subtitles: true, toWatch: false },
      { id: 34, title: 'The Girl with the Dragon Tattoo', year: 2009, genre: 'Crime, Thriller', length: 152, actors: ['Noomi Rapace','Michael Nyqvist','Lena Endre'], description: 'A journalist and a hacker investigate a womans disappearance.', image: '/images/dragon_tattoo.jpg', rating: 7.8, language: 'SV', subtitles: true, toWatch: false },
      { id: 35, title: 'Panorama', year: 2019, genre: 'Drama', length: 110, actors: ['Juan Pérez','Ana López','Carlos Díaz'], description: 'A young couple navigates love and ambition in Madrid.', image: '/images/panorama.jpg', rating: 7.4, language: 'ES', subtitles: true, toWatch: false },
      { id: 36, title: 'Cold War', year: 2018, genre: 'Romance, Drama', length: 88, actors: ['Tomasz Kot','Joanna Kulig','Borys Szyc'], description: 'A passionate love story between two musicians during the Cold War in Poland.', image: '/images/cold_war.jpg', rating: 7.6, language: 'PL', subtitles: true, toWatch: false },
      { id: 37, title: 'Dogtooth', year: 2009, genre: 'Drama', length: 95, actors: ['Christos Passalis','Mary Tsoni','Michele Valley'], description: 'Three children are raised in isolation by their parents in Greece.', image: '/images/dogtooth.jpg', rating: 7.3, language: 'GR', subtitles: true, toWatch: false },
      { id: 38, title: 'The Diving Bell and the Butterfly', year: 2007, genre: 'Biography, Drama', length: 112, actors: ['Mathieu Amalric','Emmanuelle Seigner','Marie-Josée Croze'], description: 'A man communicates his thoughts after a stroke leaves him paralyzed.', image: '/images/diving_bell.jpg', rating: 8.0, language: 'FR', subtitles: true, toWatch: false },
      { id: 39, title: 'Inception', year: 2010, genre: 'Sci-Fi, Thriller', length: 148, actors: ['Leonardo DiCaprio','Joseph Gordon-Levitt','Elliot Page'], description: 'A skilled thief enters people’s dreams to steal secrets, but is tasked with planting an idea instead.', image: '/images/inception.jpg', rating: 9.1, language: 'EN', subtitles: true, toWatch: false },
      { id: 40, title: 'Interstellar', year: 2014, genre: 'Sci-Fi, Adventure', length: 169, actors: ['Matthew McConaughey','Anne Hathaway','Jessica Chastain'], description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity’s survival.', image: '/images/interstellar.jpg', rating: 9.0, language: 'EN', subtitles: true, toWatch: false },
      { id: 41, title: 'The Lighthouse', year: 2019, genre: 'Drama, Horror', length: 109, actors: ['Robert Pattinson','Willem Dafoe'], description: 'Two lighthouse keepers descend into madness while stranded on a remote island.', image: '/images/the_lighthouse.jpg', rating: 7.5, language: 'EN', subtitles: true, toWatch: false },
      { id: 42, title: 'Minari', year: 2020, genre: 'Drama', length: 115, actors: ['Steven Yeun','Han Ye-ri','Yeri Han'], description: 'A Korean-American family starts a farm in rural Arkansas, chasing the American dream.', image: '/images/minari.jpg', rating: 7.6, language: 'EN', subtitles: true, toWatch: false },
      { id: 43, title: 'Sound of Metal', year: 2019, genre: 'Drama, Music', length: 120, actors: ['Riz Ahmed','Olivia Cooke','Paul Raci'], description: 'A drummer loses his hearing and must adapt to a new life while coming to terms with his identity.', image: '/images/sound_of_metal.jpg', rating: 7.8, language: 'EN', subtitles: true, toWatch: false },
      { id: 44, title: 'Portrait of a Lady on Fire', year: 2019, genre: 'Drama, Romance', length: 120, actors: ['Noémie Merlant','Adèle Haenel'], description: 'A forbidden affair blossoms between an aristocrat and a painter in 18th-century France.', image: '/images/portrait_of_a_lady_on_fire.jpg', rating: 8.1, language: 'FR', subtitles: true, toWatch: false },
      { id: 45, title: 'The Farewell', year: 2019, genre: 'Comedy, Drama', length: 100, actors: ['Awkwafina','Shuzhen Zhao','Tzi Ma'], description: 'A family returns to China under the guise of a fake wedding to say goodbye to their matriarch.', image: '/images/the_farewell.jpg', rating: 7.6, language: 'EN', subtitles: true, toWatch: false },
      { id: 46, title: 'Tenet', year: 2020, genre: 'Action, Sci-Fi', length: 150, actors: ['John David Washington','Robert Pattinson','Elizabeth Debicki'], description: 'A secret agent manipulates time to prevent World War III.', image: '/images/tenet.jpg', rating: 7.4, language: 'EN', subtitles: true, toWatch: false },
      { id: 47, title: 'Drive My Car', year: 2021, genre: 'Drama, Mystery', length: 179, actors: ['Hidetoshi Nishijima','Toko Miura'], description: 'A grieving actor deals with loss and relationships while preparing a stage play.', image: '/images/drive_my_car.jpg', rating: 7.9, language: 'JP', subtitles: true, toWatch: false },
      { id: 48, title: 'Dune', year: 2021, genre: 'Sci-Fi, Adventure', length: 155, actors: ['Timothée Chalamet','Rebecca Ferguson','Oscar Isaac'], description: 'A young nobleman navigates political intrigue and war on a desert planet.', image: '/images/dune.jpg', rating: 8.0, language: 'EN', subtitles: true, toWatch: false },
      { id: 49, title: 'Everything Everywhere All at Once', year: 2022, genre: 'Action, Comedy, Sci-Fi', length: 139, actors: ['Michelle Yeoh','Stephanie Hsu','Ke Huy Quan'], description: 'A laundromat owner discovers alternate versions of herself across the multiverse.', image: '/images/everything_everywhere.jpg', rating: 8.1, language: 'EN', subtitles: true, toWatch: false },
      { id: 50, title: 'The Power of the Dog', year: 2021, genre: 'Drama, Western', length: 126, actors: ['Benedict Cumberbatch','Kirsten Dunst','Jesse Plemons'], description: 'A rancher’s cruel demeanor masks complex emotions when his brother brings home a new wife and son.', image: '/images/power_of_the_dog.jpg', rating: 7.2, language: 'EN', subtitles: true, toWatch: false }

    ]
  }),

  getters: {
    topMovies(state) {
      return state.movies
        .slice()
        .sort((a, b) => b.rating - a.rating)
    },
    toWatchMovies(state) {
      return state.movies.filter(m => m.toWatch)
    },
    getMovieById: (state) => {
      return (id) => state.movies.find(m => m.id === Number(id))
    }
  },

  actions: {
    toggleToWatch(id) {
      const movie = this.movies.find(m => m.id === id)
      if (movie) movie.toWatch = !movie.toWatch
    },
    setRating(id, rating) {
      const movie = this.movies.find(m => m.id === id)
      if (movie) movie.rating = rating
    },
    setSearchFilters(filters) {
      this.searchFilters = { ...this.searchFilters, ...filters }
    }
  }
})
